
alter table transactions
    alter column id
        set generated by default restart with 612;

alter table donations
    alter column id
        set generated by default restart with 474;

alter table annadaan_bookings
    alter column id
        set generated by default restart with 93;
